// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.fn.kana = function(options) {
      var opts;
      opts = $.extend({}, $.fn.kana.defaults, options);
      alert("HEJ");
      return console.log(opts.mode);
    };
    return $.fn.kana.defaults = {
      "mode": "hiragana"
    };
  });

}).call(this);
