$ ->
    escape = (str) ->
        # Escape string for use in regex.
        str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&")

    replace_n = (str) ->
        # Replace n with ん
        re = /n[^n]/
        match = str.match re
        if match?
            str = str.replace re, "ん#{match[0][1]}"
        str

    $.fn.kana = (options) ->
        opts = $.extend {}, $.fn.kana.defaults, options

        @on "input", =>
            table = $.fn.kana.tables[opts.mode]
            v = @val()
            match = v.match(/[a-z\-\.]+$/)
            if match?
                tail = match[0]

                while tail.length
                    re = new RegExp "#{escape tail}$"
                    if tail of table
                        v = v.replace(re, table[tail])
                        break
                    tail = tail[1..]
            
            v = replace_n(v)

            @val(v)

    $.fn.kana.defaults = {
        "mode": "hiragana"
    }

    $.fn.kana.tables =
        hiragana:
            a: "あ"
            i: "い"
            u: "う"
            e: "え"
            o: "お"
            ka: "か"
            ki: "き"
            ku: "く"
            ke: "け"
            ko: "こ"
            kya: "きゃ"
            kyi: "きぃ"
            kyu: "きゅ"
            kyo: "きょ"
            kye: "きぇ"
            sa: "さ"
            si: "し"
            shi: "し"
            su: "す"
            se: "せ"
            so: "そ"
            sha: "しゃ"
            sya: "しゃ"
            syi: "しぃ"
            shu: "しゅ"
            syu: "しゅ"
            sho: "しょ"
            syo: "しょ"
            she: "しぇ"
            sye: "しぇ"
            ta: "た"
            ti: "ち"
            chi: "ち"
            tu: "つ"
            tsu: "つ"
            te: "て"
            to: "と"
            cha: "ちゃ"
            tya: "ちゃ"
            tyi: "ちぃ"
            tsi: "つぃ"
            chu: "ちゅ"
            tyu: "ちゅ"
            cho: "ちょ"
            tyo: "ちょ"
            che: "ちぇ"
            tye: "ちぇ"
            na: "な"
            ni: "に"
            nu: "ぬ"
            ne: "ね"
            no: "の"
            nya: "にゃ"
            nyi: "にぃ"
            nyu: "にゅ"
            nye: "にぇ"
            nyo: "にょ"
            ha: "は"
            hi: "ひ"
            hu: "ふ"
            he: "へ"
            ho: "ほ"
            hya: "ひゃ"
            hyi: "ひぃ"
            hyu: "ひゅ"
            hye: "ひぇ"
            hyo: "ひょ"
            fa: "ふぁ"
            fi: "ふぃ"
            fu: "ふ"
            fe: "ふぇ"
            fo: "ふぉ"
            fya: "ふゃ"
            fyi: "ふぃ"
            fyu: "ふゅ"
            fye: "ふぇ"
            fyo: "ふょ"
            ma: "ま"
            mi: "み"
            mu: "む"
            me: "め"
            mo: "も"
            mya: "みゃ"
            myi: "みぃ"
            myu: "みゅ"
            mye: "みぇ"
            myo: "みょ"
            ya: "や"
            yi: "い"
            yu: "ゆ"
            ye: "いぇ"
            yo: "よ"
            ra: "ら"
            ri: "り"
            ru: "る"
            re: "れ"
            ro: "ろ"
            rya: "りゃ"
            ryi: "りぃ"
            ryu: "りゅ"
            rye: "りぇ"
            ryo: "りょ"
            la: "ら"
            li: "り"
            lu: "る"
            le: "れ"
            lo: "ろ"
            lya: "りゃ"
            lyi: "りぃ"
            lyu: "りゅ"
            lye: "りぇ"
            lyo: "りょ"
            wa: "わ"
            wi: "うぃ"
            wu: "う"
            we: "うぇ"
            wo: "を"
            wya: "うゃ"
            wyi: "ゐ"
            wyu: "うゅ"
            wye: "ゑ"
            wyo: "うょ"
            da: "だ"
            di: "ぢ"
            du: "づ"
            de: "で"
            do: "ど"
            dya: "ぢゃ"
            dyi: "ぢぃ"
            dyu: "ぢゅ"
            dye: "ぢぇ"
            dyo: "ぢょ"
            pa: "ぱ"
            pi: "ぴ"
            pu: "ぷ"
            pe: "ぺ"
            po: "ぽ"
            pya: "ぴゃ"
            pyi: "ぴぃ"
            pyu: "ぴゅ"
            pye: "ぴぇ"
            pyo: "ぴょ"
            ga: "が"
            gi: "ぎ"
            gu: "ぐ"
            ge: "げ"
            go: "ご"
            gya: "ぎゃ"
            gyi: "ぎぃ"
            gyu: "ぎゅ"
            gye: "ぎぇ"
            gyo: "ぎょ"
            ja: "じゃ"
            ji: "じ"
            ju: "じゅ"
            je: "じぇ"
            jo: "じょ"
            jya: "じゃ"
            jyi: "じぃ"
            jyu: "じゅ"
            jye: "じぇ"
            jyo: "じょ"
            za: "ざ"
            zi: "じ"
            zu: "ず"
            ze: "ぜ"
            zo: "ぞ"
            zya: "じゃ"
            zyi: "じぃ"
            zyu: "じゅ"
            zye: "じぇ"
            zyo: "じょ"
            va: "ヴぁ"
            vi: "ヴぃ"
            vu: "ヴ"
            ve: "ヴぇ"
            vo: "ヴぉ"
            vya: "ヴゃ"
            vyu: "ヴゅ"
            vye: "ヴぃぇ"
            vyo: "ヴょ"
            ba: "ば"
            bi: "び"
            bu: "ぶ"
            be: "べ"
            bo: "ぼ"
            bya: "びゃ"
            byi: "びぃ"
            byu: "びゅ"
            bye: "びぇ"
            byo: "びょ"
            xa: "ぁ"
            xi: "ぃ"
            xu: "ぅ"
            xe: "ぇ"
            xo: "ぉ"
            xya: "ゃ"
            xyi: "ぃ"
            xyu: "ゅ"
            xye: "ぇ"
            xyo: "ょ"
            rr: "っr"
            tt: "っt"
            yy: "っy"
            pp: "っp"
            ss: "っs"
            dd: "っd"
            ff: "っf"
            gg: "っg"
            hh: "っh"
            jj: "っj"
            kk: "っk"
            ll: "ll"
            zz: "っz"
            xx: "っx"
            cc: "っc"
            vv: "っv"
            bb: "っb"
            nn: "ん"
            mm: "っm"
            "-": "ー"
            ".": "。"
